# Generated by Django 2.2.6 on 2019-11-24 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.SmallIntegerField(choices=[(0, '未启动'), (1, '投票中'), (2, '冻结中'), (3, '验证中'), (4, '已完成'), (5, '已结束')], default=0)),
                ('isPrivate', models.BooleanField(default=True)),
                ('isAnonymous', models.BooleanField(default=True)),
                ('cryptoMethod', models.SmallIntegerField(choices=[(0, '不加密'), (1, '加密一')], default=0)),
                ('question', models.CharField(max_length=300, null=True)),
                ('selections', models.CharField(max_length=300, null=True)),
                ('isAllowAbstention', models.BooleanField(default=False)),
                ('publicKey', models.CharField(max_length=300, null=True)),
                ('verifyFile', models.CharField(max_length=300, null=True)),
                ('voteResult', models.CharField(max_length=300, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-startTime',),
            },
        ),
        migrations.CreateModel(
            name='VoterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('voteResult', models.CharField(max_length=300, null=True)),
                ('voterKey', models.CharField(max_length=300, null=True)),
                ('Elections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Elections')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('voter',),
            },
        ),
    ]
